# login_axios.ts에서

`else if()`로 401에러 처리 시 `alert()`를 작성했지만
작동하지 않고 Axios 에러만 개발자도구에 뜨는 이유?

해결: `try~catch`로 `axios` 코드를 씌우고 `catch`에러 error를 받으니 front로 데이터를 넘길 수 있었다.
